### ISSUE TITLE
Figure out  how we're going to train the models

### ISSUE THREAD

**Issue by grig-guz** [ubclaunchpad/hermes#18]
A lot of storage and processing power is needed. Explore the alternatives:

1. Google Cloud
2. Colaboratory
3. You suggest

**Comment by AhmedAbdelmoneim** [comment]
Here are some alternative options:
1) FloydHub: https://www.floydhub.com/, We can get 100GB of storage + ability to run multiple jobs for $9 per month, however a standard GPU would be $12 /10 hrs
2) Crestle: https://www.crestle.com/, can submit uninterrupted jobs for $0.59/hr using GPU, and storage is $0.014/GB/day
3) Azure ML studio: we get $200 free credit when we sign up, which will last us around a couple of weeks (similar to google cloud)

Comments:
- Google cloud is cool and we can get $300 free credit when we first sign up but will only last us around a couple of weeks
- Colaboratory is the cheapest option (free) and we also get a decent GPU to work with, and for storage we can buy 100 GB of storage on google drive which costs less than $10 and connect it to colab. The downsides are I'm not sure how efficient it would be loading data from drive into colaboratory, and we can't run a process for more than 12 hours on one VM (but there's probably a workaround for this by switching VMs every 12 hours)
- FloydHub is really powerful and easy to use, however I feel like it will be a bit too expensive for us
- Azure ML studio is very similar in pricing to google cloud, and I feel like if we're going to go with one of these options google cloud seems like a better option

Overall, I feel our best option is colaboratory and store our data in google drive since we don't have a bug budget to spend on GPUs, and we can probably find a workaround for 12 hour limit on VMs
