### ISSUE TITLE
Figure out which framework we will use.

### ISSUE THREAD

**Issue by grig-guz** [ubclaunchpad/hermes#9]
## Frameworks :wrench:
We need to know what framework we'll work with. Most probable candidates so far are 

- Keras
 
- Tensorflow

- PyTorch

## Task

Do research on different frameworks, try to give and explain 3-5 reasons what each of them is good and bad at.

**Comment by Teetertater** [comment]
Tensorflow pros:
pros
Tensorboard is native
best support
better for graph optimization

cons
Isn't great with RNN's of variable witdh (our approach #1). Requires unofficial third party library to work https://github.com/tensorflow/fold


Pytorch
pros
better for debugging and writing code
"Using Pytorch makes me happy, using Tensorflow makes me sad"
easier to use variable length sequences for RNN

cons
We can still use Tensorboard, but it requires a third party library to work (https://github.com/lanpa/tensorboard-pytorch)


Notable other mentions:
I was going to compare caffe2 with pytorch, but they merged into pytorch
Keras-- easy to use for very basic stuff, but if we need to go deeper (heh), we'll need to dig into backend (tensorflow). Pytorch can do easy and hard stuff
CNTK-- Microsoft's thing, but I haven't heard any reason why it's better (only worse) than Tensorflow/Pytorch
MXNet-- New apache thing, too new and we dont' know if it's good or bad yet. Poor community support for now because it's new

**Comment by Teetertater** [comment]
https://colab.research.google.com/drive/1DDp9Zx88xboExamguYf1h51Ghar_QSTN

**Comment by grig-guz** [comment]
Nice, PyTorch it is :smiley:
